import type { Lane, Step } from '../types'

export function makeSteps(count: number, activeIndices: number[] = []): Step[] {
  return Array.from({ length: count }, (_, i) => ({
    active: activeIndices.includes(i),
    probability: 1.0,
  }))
}

export const DEFAULT_BPM = 120

export const DEFAULT_LANES: Lane[] = [
  {
    id: 'kick',
    name: 'KICK',
    sampleKey: 'kick',
    steps: makeSteps(5, [0, 2]),
    stepCount: 5,
    division: '4n',
    offset: 0,
    volume: 0.8,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#ff6b2b',
  },
  {
    id: 'snare',
    name: 'SNARE',
    sampleKey: 'snare',
    steps: makeSteps(7, [2, 5]),
    stepCount: 7,
    division: '8n',
    offset: 0,
    volume: 0.7,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#2bdeff',
  },
  {
    id: 'hihat-c',
    name: 'HH',
    sampleKey: 'hihat-closed',
    steps: makeSteps(3, [0, 1]),
    stepCount: 3,
    division: '8n',
    offset: 0,
    volume: 0.6,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#4dff91',
  },
  {
    id: 'hihat-o',
    name: 'OH',
    sampleKey: 'hihat-open',
    steps: makeSteps(4, [0, 3]),
    stepCount: 4,
    division: '8n',
    offset: 1,
    volume: 0.5,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#ffdd57',
  },
  {
    id: 'clap',
    name: 'CLAP',
    sampleKey: 'clap',
    steps: makeSteps(6, [1, 5]),
    stepCount: 6,
    division: '4n',
    offset: 1,
    volume: 0.65,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#ff9de2',
  },
  {
    id: 'perc',
    name: 'PERC',
    sampleKey: 'perc',
    steps: makeSteps(11, [0, 4, 8]),
    stepCount: 11,
    division: '4n',
    offset: 2,
    volume: 0.6,
    pitch: 0,
    muted: false,
    solo: false,
    color: '#bf7fff',
  },
]
